/**
* Ecore2Xtext Keyword Lexer
* <copyright>
*******************************************************************************/

package org.eclipse.ocl.examples.ecore2xtext;

public interface Ecore2XtextKWLexersym {
    public final static int
      Char_DollarSign = 39,
      Char_Percent = 40,
      Char__ = 41,
      Char_a = 2,
      Char_b = 14,
      Char_c = 13,
      Char_d = 12,
      Char_e = 1,
      Char_f = 18,
      Char_g = 20,
      Char_h = 25,
      Char_i = 3,
      Char_j = 42,
      Char_k = 26,
      Char_l = 7,
      Char_m = 15,
      Char_n = 5,
      Char_o = 9,
      Char_p = 10,
      Char_q = 43,
      Char_r = 6,
      Char_s = 4,
      Char_t = 8,
      Char_u = 11,
      Char_v = 19,
      Char_w = 27,
      Char_x = 16,
      Char_y = 17,
      Char_z = 28,
      Char_A = 44,
      Char_B = 21,
      Char_C = 22,
      Char_D = 45,
      Char_E = 29,
      Char_F = 46,
      Char_G = 47,
      Char_H = 48,
      Char_I = 30,
      Char_J = 49,
      Char_K = 50,
      Char_L = 31,
      Char_M = 51,
      Char_N = 32,
      Char_O = 33,
      Char_P = 23,
      Char_Q = 52,
      Char_R = 34,
      Char_S = 35,
      Char_T = 24,
      Char_U = 36,
      Char_V = 37,
      Char_W = 53,
      Char_X = 54,
      Char_Y = 55,
      Char_Z = 56,
      Char_EOF = 38;

    public final static String orderedTerminalSymbols[] = {
                 "",
                 "e",
                 "a",
                 "i",
                 "s",
                 "n",
                 "r",
                 "l",
                 "t",
                 "o",
                 "p",
                 "u",
                 "d",
                 "c",
                 "b",
                 "m",
                 "x",
                 "y",
                 "f",
                 "v",
                 "g",
                 "B",
                 "C",
                 "P",
                 "T",
                 "h",
                 "k",
                 "w",
                 "z",
                 "E",
                 "I",
                 "L",
                 "N",
                 "O",
                 "R",
                 "S",
                 "U",
                 "V",
                 "EOF",
                 "DollarSign",
                 "Percent",
                 "_",
                 "j",
                 "q",
                 "A",
                 "D",
                 "F",
                 "G",
                 "H",
                 "J",
                 "K",
                 "M",
                 "Q",
                 "W",
                 "X",
                 "Y",
                 "Z"
             };

    public final static int numTokenKinds = orderedTerminalSymbols.length;
    public final static boolean isValidForParser = true;
}
