package org.eclipse.ocl.examples.ecore2xtext;

public interface Ecore2XtextLexersym {
    public final static int
      Char_0 = 39,
      Char_1 = 40,
      Char_2 = 41,
      Char_3 = 42,
      Char_4 = 43,
      Char_5 = 44,
      Char_6 = 45,
      Char_7 = 46,
      Char_8 = 47,
      Char_9 = 48,
      Char_A = 17,
      Char_B = 49,
      Char_C = 23,
      Char_D = 50,
      Char_E = 24,
      Char_F = 25,
      Char_G = 26,
      Char_H = 51,
      Char_I = 27,
      Char_J = 52,
      Char_K = 53,
      Char_L = 54,
      Char_M = 28,
      Char_N = 55,
      Char_O = 29,
      Char_P = 18,
      Char_Q = 56,
      Char_R = 57,
      Char_S = 30,
      Char_T = 19,
      Char_U = 58,
      Char_V = 59,
      Char_W = 60,
      Char_X = 31,
      Char_Y = 61,
      Char_Z = 62,
      Char__ = 63,
      Char_a = 2,
      Char_b = 64,
      Char_c = 9,
      Char_d = 32,
      Char_e = 1,
      Char_f = 33,
      Char_g = 14,
      Char_h = 65,
      Char_i = 6,
      Char_j = 66,
      Char_k = 20,
      Char_l = 12,
      Char_m = 13,
      Char_n = 8,
      Char_o = 10,
      Char_p = 15,
      Char_q = 67,
      Char_r = 3,
      Char_s = 4,
      Char_t = 5,
      Char_u = 11,
      Char_v = 68,
      Char_w = 69,
      Char_x = 22,
      Char_y = 21,
      Char_z = 70,
      Char_HTAB = 71,
      Char_LF = 72,
      Char_CR = 73,
      Char_SPACE = 74,
      Char_PLING = 75,
      Char_DQUOTE = 76,
      Char_HASH = 77,
      Char_T_36 = 78,
      Char_T_37 = 79,
      Char_AND = 80,
      Char_SQUOTE = 81,
      Char_LPAREN = 82,
      Char_RPAREN = 83,
      Char_STAR = 84,
      Char_PLUS = 85,
      Char_COMMA = 86,
      Char_MINUS = 87,
      Char_DOT = 88,
      Char_SLASH = 34,
      Char_COLON = 16,
      Char_SEMICOLON = 89,
      Char_RANGLE = 7,
      Char_AT = 90,
      Char_LSQUARE = 91,
      Char_BSLASH = 92,
      Char_RSQUARE = 93,
      Char_CARET = 94,
      Char_T_96 = 95,
      Char_LBRACE = 96,
      Char_BAR = 97,
      Char_RBRACE = 98,
      Char_T_126 = 99,
      Char_< = 36,
      Char_? = 35,
      Char_= = 37,
      Char_EOF = 38;

    public final static String orderedTerminalSymbols[] = {
                 "",
                 "e",
                 "a",
                 "r",
                 "s",
                 "t",
                 "i",
                 "RANGLE",
                 "n",
                 "c",
                 "o",
                 "u",
                 "l",
                 "m",
                 "g",
                 "p",
                 "COLON",
                 "A",
                 "P",
                 "T",
                 "k",
                 "y",
                 "x",
                 "C",
                 "E",
                 "F",
                 "G",
                 "I",
                 "M",
                 "O",
                 "S",
                 "X",
                 "d",
                 "f",
                 "SLASH",
                 "?",
                 "<",
                 "=",
                 "EOF",
                 "0",
                 "1",
                 "2",
                 "3",
                 "4",
                 "5",
                 "6",
                 "7",
                 "8",
                 "9",
                 "B",
                 "D",
                 "H",
                 "J",
                 "K",
                 "L",
                 "N",
                 "Q",
                 "R",
                 "U",
                 "V",
                 "W",
                 "Y",
                 "Z",
                 "_",
                 "b",
                 "h",
                 "j",
                 "q",
                 "v",
                 "w",
                 "z",
                 "HTAB",
                 "LF",
                 "CR",
                 "SPACE",
                 "PLING",
                 "DQUOTE",
                 "HASH",
                 "T_36",
                 "T_37",
                 "AND",
                 "SQUOTE",
                 "LPAREN",
                 "RPAREN",
                 "STAR",
                 "PLUS",
                 "COMMA",
                 "MINUS",
                 "DOT",
                 "SEMICOLON",
                 "AT",
                 "LSQUARE",
                 "BSLASH",
                 "RSQUARE",
                 "CARET",
                 "T_96",
                 "LBRACE",
                 "BAR",
                 "RBRACE",
                 "T_126"
             };

    public final static int numTokenKinds = orderedTerminalSymbols.length;
    public final static boolean isValidForParser = true;
}
