/**
*******************************************************************************/

package org.eclipse.ocl.examples.ecore2xtext;

public interface Ecore2XtextParsersym {
    public final static int
      TK_IDENTIFIER = 13,
      TK_STRING = 61,
      TK_WS = 66,
      TK_SLASH_GT = 6,
      TK_COLON = 58,
      TK_LT = 1,
      TK_LT_SLASH = 44,
      TK_LT_SLASH_d_e_t_a_i_l_s_GT = 45,
      TK_LT_SLASH_e_A_n_n_o_t_a_t_i_o_n_s_GT = 46,
      TK_LT_SLASH_e_C_l_a_s_s_i_f_i_e_r_s_GT = 47,
      TK_LT_SLASH_e_G_e_n_e_r_i_c_T_y_p_e_GT = 48,
      TK_LT_SLASH_e_O_p_e_r_a_t_i_o_n_s_GT = 49,
      TK_LT_SLASH_e_P_a_c_k_a_g_e_s_GT = 50,
      TK_LT_SLASH_e_P_a_r_a_m_e_t_e_r_s_GT = 51,
      TK_LT_SLASH_e_S_t_r_u_c_t_u_r_a_l_F_e_a_t_u_r_e_s_GT = 52,
      TK_LT_SLASH_e_T_y_p_e_A_r_g_u_m_e_n_t_s_GT = 53,
      TK_LT_SLASH_e_c_o_r_e_COLON_E_P_a_c_k_a_g_e_GT = 54,
      TK_LT_SLASH_x_m_i_COLON_X_M_I_GT = 16,
      TK_LT_QUERY_x_m_l = 62,
      TK_LT_d_e_t_a_i_l_s = 8,
      TK_LT_e_A_n_n_o_t_a_t_i_o_n_s = 2,
      TK_LT_e_C_l_a_s_s_i_f_i_e_r_s = 7,
      TK_LT_e_G_e_n_e_r_i_c_T_y_p_e = 3,
      TK_LT_e_O_p_e_r_a_t_i_o_n_s = 9,
      TK_LT_e_P_a_r_a_m_e_t_e_r_s = 10,
      TK_LT_e_S_t_r_u_c_t_u_r_a_l_F_e_a_t_u_r_e_s = 11,
      TK_LT_e_S_u_b_p_a_c_k_a_g_e_s = 15,
      TK_LT_e_T_y_p_e_A_r_g_u_m_e_n_t_s = 12,
      TK_LT_e_c_o_r_e_COLON_E_P_a_c_k_a_g_e = 55,
      TK_LT_x_m_i_COLON_X_M_I = 56,
      TK_EQ = 5,
      TK_GT = 4,
      TK_QUERY_GT = 57,
      TK_abstract = 24,
      TK_changeable = 25,
      TK_containment = 26,
      TK_defaultValueLiteral = 27,
      TK_derived = 28,
      TK_eClassifier = 63,
      TK_eClassifiers = 23,
      TK_eExceptions = 29,
      TK_eOpposite = 30,
      TK_eSuperTypes = 31,
      TK_eType = 20,
      TK_encoding = 59,
      TK_false = 67,
      TK_instanceClassName = 32,
      TK_key = 33,
      TK_lowerBound = 34,
      TK_name = 17,
      TK_nsPrefix = 21,
      TK_nsURI = 22,
      TK_ordered = 35,
      TK_resolveProxies = 36,
      TK_serializable = 37,
      TK_source = 38,
      TK_transient = 39,
      TK_true = 68,
      TK_type = 64,
      TK_unsettable = 40,
      TK_upperBound = 41,
      TK_value = 42,
      TK_version = 60,
      TK_volatile = 43,
      TK_xmi = 18,
      TK_xmlns = 19,
      TK_xsi = 14,
      TK_EOF_TOKEN = 65,
      TK_ERROR_TOKEN = 69;

    public final static String orderedTerminalSymbols[] = {
                 "",
                 "LT",
                 "LT_e_A_n_n_o_t_a_t_i_o_n_s",
                 "LT_e_G_e_n_e_r_i_c_T_y_p_e",
                 "GT",
                 "EQ",
                 "SLASH_GT",
                 "LT_e_C_l_a_s_s_i_f_i_e_r_s",
                 "LT_d_e_t_a_i_l_s",
                 "LT_e_O_p_e_r_a_t_i_o_n_s",
                 "LT_e_P_a_r_a_m_e_t_e_r_s",
                 "LT_e_S_t_r_u_c_t_u_r_a_l_F_e_a_t_u_r_e_s",
                 "LT_e_T_y_p_e_A_r_g_u_m_e_n_t_s",
                 "IDENTIFIER",
                 "xsi",
                 "LT_e_S_u_b_p_a_c_k_a_g_e_s",
                 "LT_SLASH_x_m_i_COLON_X_M_I_GT",
                 "name",
                 "xmi",
                 "xmlns",
                 "eType",
                 "nsPrefix",
                 "nsURI",
                 "eClassifiers",
                 "abstract",
                 "changeable",
                 "containment",
                 "defaultValueLiteral",
                 "derived",
                 "eExceptions",
                 "eOpposite",
                 "eSuperTypes",
                 "instanceClassName",
                 "key",
                 "lowerBound",
                 "ordered",
                 "resolveProxies",
                 "serializable",
                 "source",
                 "transient",
                 "unsettable",
                 "upperBound",
                 "value",
                 "volatile",
                 "LT_SLASH",
                 "LT_SLASH_d_e_t_a_i_l_s_GT",
                 "LT_SLASH_e_A_n_n_o_t_a_t_i_o_n_s_GT",
                 "LT_SLASH_e_C_l_a_s_s_i_f_i_e_r_s_GT",
                 "LT_SLASH_e_G_e_n_e_r_i_c_T_y_p_e_GT",
                 "LT_SLASH_e_O_p_e_r_a_t_i_o_n_s_GT",
                 "LT_SLASH_e_P_a_c_k_a_g_e_s_GT",
                 "LT_SLASH_e_P_a_r_a_m_e_t_e_r_s_GT",
                 "LT_SLASH_e_S_t_r_u_c_t_u_r_a_l_F_e_a_t_u_r_e_s_GT",
                 "LT_SLASH_e_T_y_p_e_A_r_g_u_m_e_n_t_s_GT",
                 "LT_SLASH_e_c_o_r_e_COLON_E_P_a_c_k_a_g_e_GT",
                 "LT_e_c_o_r_e_COLON_E_P_a_c_k_a_g_e",
                 "LT_x_m_i_COLON_X_M_I",
                 "QUERY_GT",
                 "COLON",
                 "encoding",
                 "version",
                 "STRING",
                 "LT_QUERY_x_m_l",
                 "eClassifier",
                 "type",
                 "EOF_TOKEN",
                 "WS",
                 "false",
                 "true",
                 "ERROR_TOKEN"
             };

    public final static int numTokenKinds = orderedTerminalSymbols.length;
    public final static boolean isValidForParser = true;
}
