grammar org.eclipse.ocl.examples.ecore2xtext.Ecore2Xtext hidden(WS)

import "http://www.eclipse.org/emf/2002/Ecore" as ecore
import "platform:/resource/org.eclipse.ocl.examples.ecore2xtext/model/generated/Ecore2Xtext.ecore"
//generate ecore2Xtext "http://www.eclipse.org/ocl/example/ecore2xtext/Ecore2Xtext"

XMLDocument_ecore_EPackage: {XMLDocument_ecore_EPackage} '<?xml' ('version' '=' version=Terminal_String)? ('encoding' '=' encoding=Terminal_String)? '?>'
	(body+=EcoreRoot_ecore_EPackage | ('<xmi:XMI' attributes+=(XMLAttribute_xmi_version | XMLAttribute_xmlns_)* ( '/>' | ('>' (body+=XmlElement)* '</xmi:XMI>'))))
;

EcoreRoot_ecore_EPackage returns EcoreClass_ecore_EPackage_eSubpackages: {EcoreClass_ecore_EPackage_eSubpackages}
	'<ecore:EPackage' attributes+=(XMLAttribute_xmi_version | XMLAttribute_xmlns_ | XMLAttribute_xsi_type | EcoreFeature_ecore_ENamedElement_name | EcoreFeature_ecore_EPackage_nsURI | EcoreFeature_ecore_EPackage_nsPrefix | OtherAttribute)*
	( '/>' | ('>' elements+=(EcoreClass_ecore_EPackage_eClassifiers | EcoreClass_ecore_EModelElement_eAnnotations | OtherElement)* '</ecore:EPackage>'));

EcoreClass_ecore_EModelElement_eAnnotations: {EcoreClass_ecore_EModelElement_eAnnotations}
	'<eAnnotations' attributes+=(XMLAttribute_xsi_type | EcoreFeature_ecore_EAnnotation_source | OtherAttribute)*
	( '/>' | ('>' elements+=(EcoreFeature_ecore_EAnnotation_details | EcoreClass_ecore_EModelElement_eAnnotations | OtherElement)* '</eAnnotations>'));

EcoreClass_ecore_EPackage_eClassifiers: {EcoreClass_ecore_EPackage_eClassifiers}
	'<eClassifiers' attributes+=(XMLAttribute_xsi_type | EcoreFeature_ecore_ENamedElement_name | EcoreFeature_ecore_EClass_abstract | InstanceClassNameAttribute | EcoreFeature_ecore_EDataType_serializable | EcoreFeature_ecore_EClass_eSuperTypes | OtherAttribute)*
	( '/>' | ('>' elements+=(EcoreClass_ecore_EClass_eStructuralFeatures | EcoreClass_ecore_EClass_eOperations | EcoreClass_ecore_EModelElement_eAnnotations | OtherElement)* '</eClassifiers>'));

/*EcoreClass_ecore_EPackage_eClass returns ecore::EClass:
	'<eClassifiers'
	(('abstract' '=' abstract=Terminal_Boolean) | ('instanceClassName' '=' instanceClassName=Terminal_String) | ('name' '=' name=Terminal_String) | ('serializable' '=' abstract=Terminal_Boolean))*
	('xsi' ':' 'type' '=' 'ecore' '::' 'EClass')
	(('abstract' '=' abstract=Terminal_Boolean) | ('name' '=' name=Terminal_String))*
	attributes+=(EcoreFeature_ecore_EDataType_serializable | EcoreFeature_ecore_EClass_eSuperTypes | OtherAttribute)*
	( '/>' | ('>' elements+=(EcoreClass_ecore_EClass_eStructuralFeatures | EcoreClass_ecore_EClass_eOperations | EcoreClass_ecore_EModelElement_eAnnotations | OtherElement)* '</eClassifiers>'));
*/
EcoreFeature_ecore_EAnnotation_details: {EcoreFeature_ecore_EAnnotation_details}
	'<details' attributes+=(XMLAttribute_xsi_type | EcoreFeature_ecore_EStringToStringMapEntry_key | EcoreFeature_ecore_EStringToStringMapEntry_value | OtherAttribute)*
	( '/>' | ('>' elements+=(EcoreClass_ecore_EModelElement_eAnnotations | OtherElement)* '</details>'));

EcoreClass_ecore_ETypedElement_eGenericType: {EcoreClass_ecore_ETypedElement_eGenericType}
	'<eGenericType' attributes+=(XMLAttribute_xsi_type | EcoreFeature_ecore_EPackage_eClassifiers | OtherAttribute)*
	( '/>' | ('>' elements+=(EcoreClass_ecore_EGenericType_eTypeArguments | EcoreClass_ecore_EModelElement_eAnnotations | OtherElement)* '</eGenericType>'));

EcoreClass_ecore_EClass_eOperations: {EcoreClass_ecore_EClass_eOperations}
	'<eOperations' attributes+=(XMLAttribute_xsi_type | EcoreFeature_ecore_ETypedElement_eType | EcoreFeature_ecore_EOperation_eExceptions | EcoreFeature_ecore_ENamedElement_name | OtherAttribute)*
	( '/>' | ('>' elements+=(EcoreClass_ecore_EOperation_eParameters | EcoreClass_ecore_ETypedElement_eGenericType | EcoreClass_ecore_EModelElement_eAnnotations | OtherElement)* '</eOperations>'));

EcoreClass_ecore_EPackage_eSubpackages: {EcoreClass_ecore_EPackage_eSubpackages}
	'<eSubpackages' attributes+=(XMLAttribute_xsi_type | EcoreFeature_ecore_ENamedElement_name | EcoreFeature_ecore_EPackage_nsURI | EcoreFeature_ecore_EPackage_nsPrefix | OtherAttribute)*
	( '/>' | ('>' elements+=(EcoreClass_ecore_EPackage_eClassifiers | EcoreClass_ecore_ETypedElement_eGenericType | EcoreClass_ecore_EModelElement_eAnnotations | OtherElement)* '</ePackages>'));

EcoreClass_ecore_EOperation_eParameters: {EcoreClass_ecore_EOperation_eParameters}
	'<eParameters' attributes+=(XMLAttribute_xsi_type | EcoreFeature_ecore_ETypedElement_eType | EcoreFeature_ecore_ENamedElement_name | OtherAttribute)*
	( '/>' | ('>' elements+=(EcoreClass_ecore_ETypedElement_eGenericType | EcoreClass_ecore_EModelElement_eAnnotations | OtherElement)* '</eParameters>'));

EcoreClass_ecore_EClass_eStructuralFeatures: {EcoreClass_ecore_EClass_eStructuralFeatures}
	'<eStructuralFeatures' attributes+=(XMLAttribute_xsi_type | EcoreFeature_ecore_ENamedElement_name | EcoreFeature_ecore_EStructuralFeature_changeable | EcoreFeature_ecore_EStructuralFeature_transient | EcoreFeature_ecore_EStructuralFeature_derived
		| EcoreFeature_ecore_EReference_containment | EcoreFeature_ecore_ETypedElement_lowerBound | EcoreFeature_ecore_ETypedElement_upperBound | EcoreFeature_ecore_ETypedElement_ordered | EcoreFeature_ecore_EStructuralFeature_unsettable | EcoreFeature_ecore_EStructuralFeature_volatile
		| EcoreFeature_ecore_ETypedElement_eType | EcoreFeature_ecore_EReference_resolveProxies | EcoreFeature_ecore_EReference_eOpposite | EcoreFeature_ecore_EStructuralFeature_defaultValueLiteral | OtherAttribute
	)*
	( '/>' | ('>' elements+=(EcoreClass_ecore_ETypedElement_eGenericType | EcoreClass_ecore_EModelElement_eAnnotations | OtherElement)* '</eStructuralFeatures>'));

EcoreClass_ecore_EGenericType_eTypeArguments: {EcoreClass_ecore_EGenericType_eTypeArguments}
	'<eTypeArguments' attributes+=(XMLAttribute_xsi_type | EcoreFeature_ecore_EPackage_eClassifiers | OtherAttribute)*
	( '/>' | ('>' elements+=(EcoreClass_ecore_EModelElement_eAnnotations | OtherElement)* '</eTypeArguments>'));

OtherElement:
	'<' tag=Terminal_Identifier attributes+=(XmlAttribute)*
	( '/>' | ('>' elements+=(XmlElement)* '</' endTag=Terminal_Identifier '>'))
;

XmlAttribute:
	BooleanAttribute
  | IntegerAttribute
  | StringAttribute
  | OtherAttribute
;

BooleanAttribute:
	EcoreFeature_ecore_EClass_abstract
  | EcoreFeature_ecore_EStructuralFeature_changeable
  | EcoreFeature_ecore_EReference_containment
  | EcoreFeature_ecore_EStructuralFeature_defaultValueLiteral
  | EcoreFeature_ecore_EStructuralFeature_derived
  | EcoreFeature_ecore_ETypedElement_ordered
  | EcoreFeature_ecore_EReference_resolveProxies
  | EcoreFeature_ecore_EDataType_serializable
  | EcoreFeature_ecore_EStructuralFeature_transient
  | EcoreFeature_ecore_EStructuralFeature_unsettable
  | EcoreFeature_ecore_EStructuralFeature_volatile
;

IntegerAttribute:
	EcoreFeature_ecore_ETypedElement_lowerBound
  | EcoreFeature_ecore_ETypedElement_upperBound
;

StringAttribute:
	EcoreFeature_ecore_EPackage_eClassifiers
  | EcoreFeature_ecore_EOperation_eExceptions
  | EcoreFeature_ecore_EReference_eOpposite
  | EcoreFeature_ecore_EClass_eSuperTypes
  | EcoreFeature_ecore_ETypedElement_eType
  | InstanceClassNameAttribute
  | EcoreFeature_ecore_EStringToStringMapEntry_key
  | EcoreFeature_ecore_ENamedElement_name
  | EcoreFeature_ecore_EPackage_nsPrefix
  | EcoreFeature_ecore_EPackage_nsURI
  | EcoreFeature_ecore_EAnnotation_source
  | EcoreFeature_ecore_EStringToStringMapEntry_value
  | XMLAttribute_xmi_version
  | XMLAttribute_xmlns_
  | XMLAttribute_xsi_type
;

EcoreFeature_ecore_EClass_abstract:
	'abstract' '=' value=Terminal_String;

EcoreFeature_ecore_EStructuralFeature_changeable:
	'changeable' '=' value=Terminal_String;

EcoreFeature_ecore_EReference_containment:
	'containment' '=' value=Terminal_String;
	
EcoreFeature_ecore_EStructuralFeature_defaultValueLiteral:
	'defaultValueLiteral' '=' value=Terminal_String;

EcoreFeature_ecore_EStructuralFeature_derived:
	'derived' '=' value=Terminal_String;

EcoreFeature_ecore_EPackage_eClassifiers:
	'eClassifiers' '=' value=Terminal_String;

EcoreFeature_ecore_EOperation_eExceptions:
	'eExceptions' '=' value=Terminal_String;
	
EcoreFeature_ecore_EReference_eOpposite:
	'eOpposite' '=' value=Terminal_String;

EcoreFeature_ecore_EClass_eSuperTypes:
	'eSuperTypes' '=' value=Terminal_String;

EcoreFeature_ecore_ETypedElement_eType:
	'eType' '=' value=Terminal_String;

InstanceClassNameAttribute:
	'instanceClassName' '=' value=Terminal_String;

EcoreFeature_ecore_EStringToStringMapEntry_key:
	'key' '=' value=Terminal_String;

EcoreFeature_ecore_ETypedElement_lowerBound:
	'lowerBound' '=' value=Terminal_String;

EcoreFeature_ecore_ENamedElement_name:
	'name' '=' value=Terminal_String;

EcoreFeature_ecore_EPackage_nsURI:
	'nsURI' '=' value=Terminal_String;

EcoreFeature_ecore_EPackage_nsPrefix:
	'nsPrefix' '=' value=Terminal_String;

EcoreFeature_ecore_ETypedElement_ordered:
	'ordered' '=' value=Terminal_String;

EcoreFeature_ecore_EReference_resolveProxies:
	'resolveProxies' '=' value=Terminal_String;

EcoreFeature_ecore_EDataType_serializable:
	'serializable' '=' value=Terminal_String;

EcoreFeature_ecore_EAnnotation_source:
	'source' '=' value=Terminal_String;

EcoreFeature_ecore_EStructuralFeature_transient:
	'transient' '=' value=Terminal_String;

EcoreFeature_ecore_EStructuralFeature_unsettable:
	'unsettable' '=' value=Terminal_String;

EcoreFeature_ecore_ETypedElement_upperBound:
	'upperBound' '=' value=Terminal_String;

EcoreFeature_ecore_EStringToStringMapEntry_value:
	'value' '=' value=Terminal_String;

EcoreFeature_ecore_EStructuralFeature_volatile:
	'volatile' '=' value=Terminal_String;

XMLAttribute_xmi_version:
	'xmi' ':' 'version' '=' value=Terminal_String;

XMLAttribute_xmlns_:
	'xmlns' ':' ns=Terminal_Identifier '=' value=Terminal_String;

XMLAttribute_xsi_type:
	'xsi' ':' 'type' '=' value=Terminal_String;

OtherAttribute:
	tag=IDENTIFIER '=' value=Terminal_String;

XmlElement:
	EcoreClass_ecore_EClass_eOperations
  | EcoreClass_ecore_EClass_eStructuralFeatures
  | EcoreClass_ecore_EGenericType_eTypeArguments
  | EcoreClass_ecore_EModelElement_eAnnotations
  | EcoreClass_ecore_EOperation_eParameters
  | EcoreClass_ecore_EPackage_eClassifiers
  | EcoreClass_ecore_EPackage_eSubpackages
  | EcoreClass_ecore_ETypedElement_eGenericType
  | EcoreFeature_ecore_EAnnotation_details
  | OtherElement
;

Terminal_Boolean returns ecore::EBoolean : 'true' | 'false';

Terminal_String : STRING;

Terminal_Identifier : IDENTIFIER
  | 'abstract'
  | 'changeable'
  | 'containment'
  | 'defaultValueLiteral'
  | 'derived'
  | 'eClassifier'
  | 'eExceptions'
  | 'eOpposite'
  | 'eSuperTypes'
  | 'eType'
  | 'encoding'
  | 'instanceClassName'
  | 'key'
  | 'lowerBound'
  | 'name'
  | 'nsURI'
  | 'nsPrefix'
  | 'ordered'
  | 'resolveProxies'
  | 'serializable'
  | 'source'
  | 'transient'
  | 'unsettable'
  | 'upperBound'
  | 'value'
  | 'version'
  | 'volatile'
  | 'xmi'
  | 'xsi'
;

//terminal LETTER  	: 'a'..'z'|'A'..'Z';
//terminal DIGIT  	: '0'..'9';
//terminal PUNCT		: '_' | '.' | '-' | '|' | '~' | '{' | '}' | '`' | '[' | ']' | '^' | '!' | '@' | ';' | ',' | '*' | '+' | '(' | ')' | '&' | '\'' | '\\' | '$' | '%' | '#';
//terminal WS_CHAR	: (' '|'\t'|'\r'|'\n'/*|'\f'*/);

//terminal STRING	: '"' (
//					('&' (('a' 'm' 'p') | ('a' 'p' 'o' 's') | ('g' 't') | ('l' 't') | ('q' 'u' 'o' 't')) ';')
//					| ' '..'!' /* " */ | '#'..'%' /* & ' */ | '('..';' /* < */ | '='..'=' /* > */ | '?'..'~' 
//					)* '"';
/** LPG cannot negate, so enumerate all positives, XML entities need pruning later */
terminal STRING	: '"' (' '..'!' /* " */ | '#'..'~')* '"'; 
terminal IDENTIFIER : ('a'..'z'|'A'..'Z'|'_'..'_') ('a'..'z'|'A'..'Z'|'_'..'_'|'0'..'9')*;	// xtext2lpg only considers ranges for letters etc
terminal WS			: (' '|'\t'|'\r'|'\n'/*|'\f'*/)+;

//terminal ANY_OTHER: .;
	