/*******************************************************************************
 * Copyright (c) 2015, 2018 Willink Transformations and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v2.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v20.html
 *
 * Contributors:
 *     E.D.Willink - initial API and implementation
 *******************************************************************************/
/*
 * generated by Xtext
 */
package org.eclipse.ocl.xtext.base;

import org.eclipse.ocl.xtext.base.cs2text.user.UserModelAnalysis;
import org.eclipse.ocl.xtext.base.cs2text.xtext.GrammarAnalysis;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class BaseRuntimeModule extends org.eclipse.ocl.xtext.base.AbstractBaseRuntimeModule
{
	public Class<? extends GrammarAnalysis> bindGrammarAnalysis() {
		return GrammarAnalysis.class;
	}

	public Class<? extends UserModelAnalysis> bindUserModelAnalysis() {
		return UserModelAnalysis.class;
	}
}
